// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlK1q_WIxXZ6VghBRQ5xA9kvCvLP1XExY',
    appId: '1:929026684024:web:ea57e6072cb0d8693d298d',
    messagingSenderId: '929026684024',
    projectId: 'rewardy-b7efa',
    authDomain: 'rewardy-b7efa.firebaseapp.com',
    storageBucket: 'rewardy-b7efa.firebasestorage.app',
    measurementId: 'G-PGVTHVWPMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATg92lId9sVAXTHVk5e07G4Nopz4vzBww',
    appId: '1:929026684024:android:d0809528d5d4a1bb3d298d',
    messagingSenderId: '929026684024',
    projectId: 'rewardy-b7efa',
    storageBucket: 'rewardy-b7efa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa8c1GdAi7IuFadwQSonOPg3wPWrEoAvk',
    appId: '1:929026684024:ios:0b605b796ce870413d298d',
    messagingSenderId: '929026684024',
    projectId: 'rewardy-b7efa',
    storageBucket: 'rewardy-b7efa.firebasestorage.app',
    iosBundleId: 'com.example.rewardy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa8c1GdAi7IuFadwQSonOPg3wPWrEoAvk',
    appId: '1:929026684024:ios:0b605b796ce870413d298d',
    messagingSenderId: '929026684024',
    projectId: 'rewardy-b7efa',
    storageBucket: 'rewardy-b7efa.firebasestorage.app',
    iosBundleId: 'com.example.rewardy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlK1q_WIxXZ6VghBRQ5xA9kvCvLP1XExY',
    appId: '1:929026684024:web:c8dde2424ae5b9f93d298d',
    messagingSenderId: '929026684024',
    projectId: 'rewardy-b7efa',
    authDomain: 'rewardy-b7efa.firebaseapp.com',
    storageBucket: 'rewardy-b7efa.firebasestorage.app',
    measurementId: 'G-6XTTXYQP56',
  );
}
